### ISSUE TITLE
Allow vi modelines compatibility

### ISSUE THREAD

**Issue by nolange** [pestilence669/VimModelines#16]
Is there a good reason vi modelines like `# vi:et:ts=2` arent supported?
Since I dont need anything fancy, just setting tabs I settled on this line some years ago after testing support in multiple editors, the basic idea being that anything that supports the vi**m** modelines will support vi too.

using `# vim:et:ts=2` works by the way.

**Comment by pestilence669** [comment]
No. No good reason. Good catch and thanks for taking the time to reach out.

I'll work this into the next update.

**Comment by perchrc** [comment]
I have made the following local fix to vimmodelines.py to get around this:

`__modeline_RX = re.compile('(?:vim|vi)(?:\d*):\s*(?:set)?\s*(.*)$')`

**Comment by nolange** [comment]
Sounds easy enough. Maybe add |ex too.

http://vimdoc.sourceforge.net/htmldoc/options.html#auto-setting

**Comment by pestilence669** [comment]
Addressed in release 1.0.5
